language: node_js
node_js:
  - "0.12"
  - "4.2"
  - "5"

sudo: false

cache:
  directories:
    - node_modules

before_install:
  - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
  - npm config set spin false
  - npm install -g npm

install:
  - npm install -g bower
  - npm install -g codecov
  - npm install
  - bower install

script:
  - npm test

after_success:
  - codecov -e TRAVIS_NODE_VERSION
